apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kepler
  namespace: kepler
spec:
  interval: 10m
  install:
    createNamespace: true
  chart:
    spec:
      chart: kepler
      sourceRef:
        kind: HelmRepository
        name: kepler
        namespace: kepler

spec:
  values:
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: false
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - operator: Exists
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 400Mi
