apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kepler
  namespace: kepler
spec:
  interval: 1m
  install:
    createNamespace: true
  chart:
    spec:
      chart: kepler
      sourceRef:
        kind: HelmRepository
        name: kepler
        namespace: kepler
      # opcjonalnie przypnij zakres wersji (semver):
      # version: ">=0.6.0"
  valuesFrom:
    - kind: ConfigMap
      name: kepler-values
      valuesKey: values.yaml
  # alternatywnie: użyj spec.values zamiast valuesFrom
