apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kepler
  namespace: kepler
spec:
  interval: 10m
  url: https://sustainable-computing-io.github.io/kepler-helm-chart
