apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kepler
  namespace: kepler
spec:
  interval: 10m
  url: https://github.com/sustainable-computing-io/kepler-helm-chart.git
